### ISSUE TITLE
Wrong typedefinition for "require"

### ISSUE THREAD

**Issue by Masterrg** [SK83RJOSH/types-jcmp#1]
Instead of providing a bad typedefinition of "require" you may remove it and:

- add a dependency on "typings"
- extend the current readme and tell the user to run ` typings i dt~node` or `typings i dt~node --global` **after** `npm install`

I think we better teach the "new developers" how to deal with typedefinitions the correct way, instead of introducing a hacky solution.

**Comment by SK83RJOSH** [comment]
Added a README to this repo describing how to install the node typings, and used @types/node instead of dt~node since `@types` is generally preferred in TypeScript 2.0

Thanks for giving me some motivation 👍
